spring:

  application:
    name: nimbi

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/nimbi
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    validate-on-migrate: true
    default-schema: public
    locations: classpath:db/migration

logging:
  level:
    root: INFO

otel:
  host: ${OTEL_HOST}

management:
  tracing:
    sampling:
      probability: 1.0

d2:
  runewizard:
    token: ${D2_RUNEWIZARD_TOKEN}

discord:
  token: ${DISCORD_TOKEN}
